### ISSUE TITLE
Bundling App on Windows Fails

### ISSUE THREAD

**Issue by Arryk** [PeaceFounder/AppBundler.jl#14]
Hi,

I am trying to build a very simple application to test the bundler on Windows, but the application returns an error.

I have a very simple main.jl that contains
```julia
println("main.jl has been called!")
```
My Project.toml file

```toml
name = "TestBundle"
authors = ["AH"]
version = "0.0.1"

[bundle]
APP_NAME = "TestBundle"
APP_DESCRIPTION = "An app to TestBundle"
APP_DISPLAY_NAME = "TestBundle"
APP_SUMMARY = "An app to rTestBundle"
BUNDLE_IDENTIFIER = "none"
PUBLISHER = "CN=AH"
PUBLISHER_DISPLAY_NAME = "AH"
WITH_SPLASH_SCREEN = true
```

After that I run in the REPL
`AppBundler.bundle_app(Windows(:x86_64), "TestBundle", "build/TestBundle.zip")`

And I get a lots of errors
<img width="596" alt="image" src="https://github.com/user-attachments/assets/2e698329-1027-4b9e-94af-df61c0daa6cb">

Every single filename has an "issue" with invalid characters.

I am running Julia 1.10.4 on Windows 11 Pro 22H2 (build 22621.1413)

Any idea how to get this to work ?
